title: "Cards"
description: |
  The form can be used when creating a product description. Use corresponding icon with product description

patterns:
  polaroid:
    title: "polaroid"
    description: |
      Use this type of card for products
    fields:
      - name: title
        type: string
        example: "cap libecap"
      - name: details
        type: string
        example: "me"
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
    width: "20em"

  sticky-note:
    title: "sticky-note"
    description: |
      Use this type of card for short text, ie titles for projects
    fields:
      - name: title
        type: string
        example: "Project 1"
      - name: description
        type: string
        example: "packaging"
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
    width: "20em"

  image-on-paper:
    title: "image on paper"
    description: |
      Use this type of card for images with a border
    fields:
      - name: title
        type: string
        example: "cap libecap"
      - name: details
        type: string
        example: "me"
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
    width: "80%"
