title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is require. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    fields:
      - name: text
        type: string
        example: "hola"
      - name: url
        type: url
        example: "/products/"
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: "12em"
  ghost:
    fields:
      - name: text
        type: string
        example: "hello"
      - name: url
        type: url
        example: "/products/"
    title: "Ghost"
    description: |
      The ghost button is specifically for banners, where it will be placed in front of busy images.
    background: "--color-primary-light"
    width: "12em"
  light:
    fields:
      - name: text
        type: string
        example: "hello"
      - name: url
        type: url
        example: "/products/"
    title: "Light"
    description: |
      The light button is for dark backgrounds, where it will be used instead of the basic button.
    width: "12em"
  form-btn:
    fields:
      - name: text
        type: string
        example: "Submit"
      - name: url
        type: url
        example: "/products/"
    title: "Send Form"
    description: |
      Use this button at the end of any forms
    width: "12em"
