title: "Sections"
description: |
  To help seperate content into their own categories

patterns:
  project-brief:
    fields:
      - name: heading
        type: string
      - name: text
        type: string
      - name: image
        type: url
    title: "Project Brief"
    description: |
      Use this layout for the project brief and description
    width: "80%"


  text-and-image:
    title: "text and image"
    description: |
      Use this type of card for image accompanying text
    fields:
      - name: title
        type: string
        example: "cap libecap"
      - name: details
        type: string
        example: "me"
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
    width: "80%"

  image-text-inline:
    title: "text and image inline at medium and large sizes"
    description: |
      Use this type of card for image accompanying text
    fields:
      - name: title
        type: string
        example: "cap libecap"
      - name: details
        type: string
        example: "me"
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
    width: "80%"

  see-more:
    title: "See More Work"
    description: |
      Use this for the bottom of the accompanying pages to redirect to work section
    fields:
      - name: title
        type: string
        example: "cap libecap"
      - name: details
        type: string
        example: "me"
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
    width: "80%"
