title: "Cards"
description: |
  The form can be used when creating a product description. Use corresponding icon with product description

patterns:
  figure:
    title: "figure with caption"
    description: |
      Use this type of card for products
    fields:
      - name: title
        type: string
        example: "cap libecap"
      - name: details
        type: string
        example: "me"
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
    width: "20em"

  image-card:
    title: "Image Card"
    description: |
      Use this type of card on the indext to direct user to project overview page
    fields:
      - name: title
        type: string
        example: "cap libecap"
      - name: details
        type: string
        example: "me"
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
